#  BoxLayout:
    #  orientation: "vertical"
    #  Button:
        #  text: 'one'
    #  Button:
        #  text: 'two'
    #  BoxLayout
        #  orientation: "horizontal"
        #  Button:
            #  text: 'three'
        #  Button:
            #  text: 'four'

GridLayout:
    rows: 2
    cols: 3
    Button:
        text: 'one'
    Label:
        text: 'two'
    Button:
        text: 'three'
    Label:
        text: 'four'
    Button:
        text: 'five'
    Label:
        text: 'six'